export const CACHE_KEY_PREFIX = "adb_pkg_cache_";

export const BLACKLIST = [
  "android",
  "com.android.systemui",
  "com.android.settings",
  "com.android.phone",
  "com.android.contacts",
  "com.miui.securitycenter",
];

export const BLOATWARE_PRESETS = {
  xiaomi: [
    "com.xiaomi.payment",
    "com.android.browser",
    "com.miui.player",
    "com.sohu.inputmethod.sogou.xiaomi",
    "com.xiaomi.joyose",
    "com.google.android.apps.youtube.music",
    "com.miui.voiceassist",
    "com.google.android.videos",
    "com.android.bips",
    "com.google.android.apps.tachyon",
    "com.milink.service",
    "com.mi.globalbrowser",
    "com.miui.bugreport",
    "com.google.android.apps.subscriptions.red",
    "com.miui.miservice",
    "com.google.android.projection.gearhead",
    "com.xiaomi.mipicks",
    "com.xiaomi.market",
    "com.miui.videoplayer",
    "com.miui.yellowpage",
    "com.tencent.soter.soterserver",
    "com.miui.daemon",
    "com.xiaomi.simactivate.service",
    "com.miui.analytics",
    "com.miui.personalassistant",
    "com.android.printspooler",
    "com.miui.cloudservice",
    "com.miui.cloudbackup",
    "com.xiaomi.glgm",
    "com.baidu.input_mi",
    "com.google.android.apps.safetyhub",
    "com.miui.micloudsync",
    "com.google.android.marvin.talkback",
    "com.miui.nextpay",
    "com.xiaomi.aiasst.vision",
    "com.xiaomi.aicr",
    "com.unionpay.tsmservice.mi",
    "com.miui.huanji",
    "com.iflytek.inputmethod.miui",
    "com.miui.fm",
    "com.amazon.appmanager",
    "com.mipay.wallet",
    "com.facebook.appmanager",
    "com.mi.globalminusscreen",
    "com.miui.msa.global",
    "com.facebook.services",
    "com.facebook.system",
    "com.miui.hybrid",
    "com.miui.hybrid.accessory",
    "com.xiaomi.gamecenter.sdk.service",
    "com.miui.greenguard",
    "com.miui.touchassistant",
    "com.mi.health",
    "com.xiaomi.micloud.sdk",
    "com.xiaomi.aiasst.service",
    "com.xiaomi.finddevice",
    "com.miui.backup",
    "com.xiaomi.mi_connect_service",
    "com.xiaomi.mirror",
    "com.xiaomi.digitalkey",
    "com.miui.fmservice",
    "com.miui.tsmclient",
    "com.miui.carlink",
    "com.miui.notes",
    "com.xiaomi.mibrain.speech",
    "com.xiaomi.mtb",
    "com.miui.audiomonitor",
    "com.miui.powerkeeper",
    "com.miui.newmidrive",
    "com.miui.vsimcore",
    "com.miui.systemAdSolution",
    "com.miui.contentcatcher",
    "com.miui.cleanmaster",
    "com.miui.compass",
    "com.miui.android.fashiongallery",
    "com.miui.mishare.connectivity",
    "com.mi.global.shop",
    "com.xiaomi.gamecenter",
    "cn.wps.xiaomi.abroad.lite",
  ],
  samsung: [
    "com.samsung.android.bixby.agent",
    "com.samsung.android.app.spage",
    "com.samsung.android.service.peoplestripe",
    "com.samsung.android.app.routines",
    "com.samsung.android.game.gamehome",
    "com.samsung.android.game.gametools",
    "com.samsung.android.aremoji",
    "com.sec.android.app.sbrowser",
  ],
  google: [
    "com.android.egg",
    "com.android.bips",
    "com.android.printspooler",
    "com.android.stk",
    "com.android.wallpaper.livepicker",
    "com.android.chrome",
    "com.google.android.apps.tachyon",
    "com.google.android.apps.youtube.music",
    "com.google.android.apps.docs",
    "com.google.android.apps.photos",
    "com.google.android.apps.wellbeing",
    "com.google.android.marvin.talkback",
    "com.google.android.videos",
    "com.google.ar.lens",
    "com.google.android.as.oss",
  ],
};

export const FRIENDLY_NAMES: Record<string, string> = {
  "com.xiaomi.payment": "Mi Pay (Thanh toán Xiaomi)",
  "com.android.browser": "Trình duyệt MIUI gốc (Mi Browser)",
  "com.miui.player": "Mi Music (Nhạc Xiaomi)",
  "com.sohu.inputmethod.sogou.xiaomi": "Bàn phím Sogou (Xiaomi Edition)",
  "com.xiaomi.joyose": "Joyose (Game Analytics / Throttle)",
  "com.google.android.apps.youtube.music": "YouTube Music",
  "com.miui.voiceassist": "Xiao AI (Trợ lý giọng nói)",
  "com.google.android.videos": "Google TV / Play Movies",
  "com.android.bips": "Dịch vụ in ấn Android (BIPS)",
  "com.google.android.apps.tachyon": "Google Meet / Duo",
  "com.milink.service": "Mi Link Service (Chiếu màn hình)",
  "com.mi.globalbrowser": "Mi Browser Global",
  "com.miui.bugreport": "Mi Bug Report (Báo cáo lỗi)",
  "com.google.android.apps.subscriptions.red": "Google One",
  "com.miui.miservice": "Mi Service (Hỗ trợ khách hàng)",
  "com.google.android.projection.gearhead": "Android Auto",
  "com.xiaomi.mipicks": "GetApps (Cửa hàng ứng dụng rác)",
  "com.xiaomi.market": "Mi App Store",
  "com.miui.videoplayer": "Mi Video (Xem video Xiaomi)",
  "com.miui.yellowpage": "Mi Trang vàng (Yellow Pages)",
  "com.tencent.soter.soterserver": "Tencent Soter Service",
  "com.miui.daemon": "MiuiDaemon (Theo dõi ngầm)",
  "com.xiaomi.simactivate.service": "SIM Activation Service",
  "com.miui.analytics": "MIUI Analytics (Theo dõi)",
  "com.miui.personalassistant": "App Vault (Trợ lý cá nhân)",
  "com.android.printspooler": "Print Spooler (Bộ quản lý in)",
  "com.miui.cloudservice": "Mi Cloud Service (Đám mây)",
  "com.miui.cloudbackup": "Mi Cloud Backup (Sao lưu)",
  "com.xiaomi.glgm": "Xiaomi Game Center (Trò chơi)",
  "com.baidu.input_mi": "Bàn phím Baidu (Xiaomi Edition)",
  "com.google.android.apps.safetyhub": "Google Safety Hub",
  "com.miui.micloudsync": "Mi Cloud Sync (Đồng bộ đám mây)",
  "com.google.android.marvin.talkback": "TalkBack (Hỗ trợ truy cập)",
  "com.miui.nextpay": "Mi Next Pay",
  "com.xiaomi.aiasst.vision": "Mi AI Vision (Nhận diện hình ảnh)",
  "com.xiaomi.aicr": "Mi AI Screen Recognition",
  "com.unionpay.tsmservice.mi": "UnionPay TSM Service",
  "com.miui.huanji": "Mi Mover (Chuyển dữ liệu)",
  "com.iflytek.inputmethod.miui": "Bàn phím iFlyTek (Xiaomi)",
  "com.miui.fm": "Đài FM (Miui FM)",
  "com.amazon.appmanager": "Amazon App Manager",
  "com.mipay.wallet": "Mi Wallet (Ví Mi Pay)",
  "com.facebook.appmanager": "Facebook App Manager",
  "com.mi.globalminusscreen": "App Vault (Minus Screen)",
  "com.miui.msa.global": "MSA (Quảng cáo hệ thống)",
  "com.facebook.services": "Facebook Services",
  "com.facebook.system": "Facebook System",
  "com.miui.hybrid": "Quick Apps (Dữ liệu ngầm)",
  "com.miui.hybrid.accessory": "Quick Apps Accessory",
  "com.xiaomi.gamecenter.sdk.service": "Game Center SDK",
  "com.miui.greenguard": "Green Guard (Quản lý trẻ em)",
  "com.miui.touchassistant": "Quick Ball (Phím ảo trợ năng)",
  "com.mi.health": "Mi Health / Fitness",
  "com.xiaomi.micloud.sdk": "Mi Cloud SDK",
  "com.xiaomi.aiasst.service": "AI Assistant Service",
  "com.xiaomi.finddevice": "Mi Find Device (Tìm thiết bị)",
  "com.miui.backup": "Mi Backup & Restore",
  "com.xiaomi.mi_connect_service": "Mi Connect Service",
  "com.xiaomi.mirror": "Mi Mirror (Phản chiếu)",
  "com.xiaomi.digitalkey": "Digital Car Key",
  "com.miui.fmservice": "FM Radio Service",
  "com.miui.tsmclient": "Mi TSM Client (NFC Card)",
  "com.miui.carlink": "Mi CarLink (Kết nối ô tô)",
  "com.miui.notes": "Mi Notes (Ghi chú Xiaomi)",
  "com.xiaomi.mibrain.speech": "Mi Brain Speech Engine",
  "com.xiaomi.mtb": "Xiaomi MTB Service",
  "com.miui.audiomonitor": "Audio Monitor (Karaoke)",
  "com.miui.powerkeeper": "Mi Powerkeeper",
  "com.miui.newmidrive": "Mi Cloud Drive",
  "com.miui.vsimcore": "Mi Roaming (Virtual SIM)",
  "com.miui.systemAdSolution": "System Ad Solution",
  "com.miui.contentcatcher": "Content Catcher",
  "com.miui.cleanmaster": "System Cleaner (Dọn rác)",
  "com.miui.compass": "Mi Compass (La bàn)",
  "com.miui.android.fashiongallery": "Wallpaper Carousel (Hình nền động)",
  "com.miui.mishare.connectivity": "Mi Share",
  "com.mi.global.shop": "Mi Store",
  "com.xiaomi.gamecenter": "Game Center",
  "cn.wps.xiaomi.abroad.lite": "WPS Office Xiaomi Lite",
  "com.android.chrome": "Google Chrome",
  "com.google.android.apps.photos": "Google Photos",
};
